ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR'] #changed
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  MAP_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 90
    TYPE: 'MAP_SENSOR'
  EGOMOTION:
    TYPE: 'EGOMOTION'
    HFOV: 90
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.2
  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2

  # For our profiling tutorial, let's disable the stop action. This will lengthen our
  # episodes and avoid the problem of environment resets being over-represented in
  # early training.
  POSSIBLE_ACTIONS: ["MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]

DATASET:
 TYPE: PointNav-v1
 SPLIT: train
 DATA_PATH: data/datasets/pointnav/gibson/v1/{split}/{split}.json.gz
