BASE_TASK_CONFIG_PATH: "configs/tasks/pointnav.yaml"
TRAINER_NAME: "ppo"
ENV_NAME: "NavRLEnv"
VIDEO_OPTION: []
NUM_PROCESSES: 2
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
NUM_UPDATES: 100
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 1000

RL:
  PPO:
    # ppo params
    clip_param: 0.1
    ppo_epoch: 4
    num_mini_batch: 1
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.5
    # these are reduced 4x for msi laptop
    num_steps: 32
    hidden_size: 128
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: True
    use_linear_lr_decay: True
    reward_window_size: 50
