BASE_TASK_CONFIG_PATH: config/habitat_pointnav_config.yaml
CHECKPOINT_FOLDER: models/checkpoints_Baseline_20211209190400
CHECKPOINT_INTERVAL: 10
ENV_NAME: NavRLEnv
EVAL_CKPT_PATH_DIR: models/checkpoints_Baseline_20211209190400
LOG_INTERVAL: 1
NUM_PROCESSES: 1
NUM_UPDATES: 20
RL:
  PPO:
    clip_param: 0.1
    entropy_coef: 0.01
    eps: 1.0e-05
    gamma: 0.99
    hidden_size: 512
    lr: 0.00025
    max_grad_norm: 0.5
    num_mini_batch: 1
    num_steps: 128
    ppo_epoch: 4
    reward_window_size: 50
    tau: 0.95
    use_gae: true
    use_linear_clip_decay: true
    use_linear_lr_decay: true
    value_loss_coef: 0.5
SENSORS:
- RGB_SENSOR
SIMULATOR_GPU_ID: 0
TENSORBOARD_DIR: results/tb_Baseline_20211209190400
TEST_EPISODE_COUNT: 2
TORCH_GPU_ID: 0
TRAINER_NAME: ppo
VIDEO_DIR: video_dir
VIDEO_OPTION:
- disk
- tensorboard
