DATASET:
  DATA_PATH: data/datasets/pointnav/gibson/v1/{split}/{split}.json.gz
  SPLIT: train
  TYPE: PointNav-v1
ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    SENSORS:
    - RGB_SENSOR
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    HEIGHT: 256
    WIDTH: 256
TASK:
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass
  MEASUREMENTS:
  - DISTANCE_TO_GOAL
  - SUCCESS
  - SPL
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    DIMENSIONALITY: 2
    GOAL_FORMAT: POLAR
  POSSIBLE_ACTIONS:
  - MOVE_FORWARD
  - TURN_LEFT
  - TURN_RIGHT
  - STOP
  SENSORS:
  - POINTGOAL_WITH_GPS_COMPASS_SENSOR
  SUCCESS:
    SUCCESS_DISTANCE: 0.2
  SUCCESS_DISTANCE: 0.2
  TYPE: Nav-v0
